### ISSUE TITLE
Strange delay when using suspense

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#133]
Please have a look at the following demo:
https://codesandbox.io/s/boring-shadow-2kw63?file=/src/index.js

When you click on one of the buttons you will notice some kind of delay of maybe 400 ms or something. Wouldn't it be better if there would not be such a delay by default but instead could be configurable by using `<Suspense delay={400} fallback={...}> ... </Suspense>`?

**Comment by thysultan** [comment]
Isn't that from `getRandomNumberDelayed` that returns a promise with a 3s delay(3000ms)?

**Comment by thysultan** [comment]
NVM, i see what you mean(the showing of the loading state).

**Comment by thysultan** [comment]
Yes, there's a delay, maybe we can make it 100ms(default) and allow the delay prop that you suggest.

**Comment by Zolmeister** [comment]
Indeed, it's 600ms
https://github.com/dyo/dyo/blob/72ec2704710b911986cd9a3ffd292da7fdba3583/src/Suspense.js#L122
https://github.com/dyo/dyo/blob/72ec2704710b911986cd9a3ffd292da7fdba3583/src/Enum.js#L9

I'm not sure it should have a default timeout. I set one for server-side rendering at the top of the render loop, but otherwise timeout should be handled by the suspense promise itself.

**Comment by thysultan** [comment]
The 'default timeout' does not affect server-side rendering as you cannot interact with the ui in server-side rendering. the default timeout only takes effect for subsequent events after the initial rendering(i.e in this case the click event) — in this example the "Loading..." timeout doesn't happen for the initial load.

The idea behind the timeout was to avoid a loading state if the network response time is fast enough as to not be perceptible, but 600ms seemed to be too much thus my suggestion for 100ms.

We should probably call it `timeout` instead of delay to more closely map with it's intended meaning.

**Comment by Zolmeister** [comment]
Looks like React does timeout configuration through [`useTransition`](https://reactjs.org/docs/concurrent-mode-reference.html#usetransition) (though not sure of default).

**Comment by thysultan** [comment]
Per https://github.com/facebook/react/pull/19703 it looks like they removed that config opt.
